// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Project:         newProject(db, opts...),
		ProjectHasUser:  newProjectHasUser(db, opts...),
		ProjectSafe:     newProjectSafe(db, opts...),
		SchemaMigration: newSchemaMigration(db, opts...),
		Session:         newSession(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Project         project
	ProjectHasUser  projectHasUser
	ProjectSafe     projectSafe
	SchemaMigration schemaMigration
	Session         session
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Project:         q.Project.clone(db),
		ProjectHasUser:  q.ProjectHasUser.clone(db),
		ProjectSafe:     q.ProjectSafe.clone(db),
		SchemaMigration: q.SchemaMigration.clone(db),
		Session:         q.Session.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Project:         q.Project.replaceDB(db),
		ProjectHasUser:  q.ProjectHasUser.replaceDB(db),
		ProjectSafe:     q.ProjectSafe.replaceDB(db),
		SchemaMigration: q.SchemaMigration.replaceDB(db),
		Session:         q.Session.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Project         *projectDo
	ProjectHasUser  *projectHasUserDo
	ProjectSafe     *projectSafeDo
	SchemaMigration *schemaMigrationDo
	Session         *sessionDo
	User            *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Project:         q.Project.WithContext(ctx),
		ProjectHasUser:  q.ProjectHasUser.WithContext(ctx),
		ProjectSafe:     q.ProjectSafe.WithContext(ctx),
		SchemaMigration: q.SchemaMigration.WithContext(ctx),
		Session:         q.Session.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
