// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectSafe = "project_saves"

// ProjectSafe mapped from table <project_saves>
type ProjectSafe struct {
	ProjectSaveID string    `gorm:"column:project_save_id;primaryKey" json:"project_save_id"`
	ProjectID     string    `gorm:"column:project_id;not null" json:"project_id"`
	Editor        string    `gorm:"column:editor" json:"editor"`
	Object        string    `gorm:"column:object" json:"object"`
	SavedBy       string    `gorm:"column:saved_by;primaryKey" json:"saved_by"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:2024-07-08 21:48:10.365423+09" json:"updated_at"`
}

// TableName ProjectSafe's table name
func (*ProjectSafe) TableName() string {
	return TableNameProjectSafe
}
