// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ProjectID string    `gorm:"column:project_id;primaryKey" json:"project_id"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	OwnerID   string    `gorm:"column:owner_id;not null" json:"owner_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:2024-07-08 21:48:10.365423+09" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:2024-07-08 21:48:10.365423+09" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
