// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID    string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Icon      string    `gorm:"column:icon;not null" json:"icon"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:2024-07-08 21:48:10.365423+09" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:2024-07-08 21:48:10.365423+09" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
